from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(316, 332)
        Dialog.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.Title = QtWidgets.QLabel(parent=Dialog)
        self.Title.setGeometry(QtCore.QRect(70, 20, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.IDInput = QtWidgets.QLineEdit(parent=Dialog)
        self.IDInput.setGeometry(QtCore.QRect(90, 70, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.IDInput.setFont(font)
        self.IDInput.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.IDInput.setText("")
        self.IDInput.setObjectName("IDInput")
        self.IDLabel = QtWidgets.QLabel(parent=Dialog)
        self.IDLabel.setGeometry(QtCore.QRect(50, 70, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.IDLabel.setFont(font)
        self.IDLabel.setObjectName("IDLabel")
        self.CandidatesLabel = QtWidgets.QLabel(parent=Dialog)
        self.CandidatesLabel.setGeometry(QtCore.QRect(100, 110, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CandidatesLabel.setFont(font)
        self.CandidatesLabel.setObjectName("CandidatesLabel")
        self.JaneVote = QtWidgets.QRadioButton(parent=Dialog)
        self.JaneVote.setGeometry(QtCore.QRect(110, 150, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.JaneVote.setFont(font)
        self.JaneVote.setObjectName("JaneVote")
        self.JohnVote = QtWidgets.QRadioButton(parent=Dialog)
        self.JohnVote.setGeometry(QtCore.QRect(110, 180, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.JohnVote.setFont(font)
        self.JohnVote.setObjectName("JohnVote")
        self.Submit = QtWidgets.QPushButton(parent=Dialog)
        self.Submit.setGeometry(QtCore.QRect(50, 230, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Submit.setFont(font)
        self.Submit.setAutoFillBackground(False)
        self.Submit.setObjectName("Submit")
        self.AlreadyVoted = QtWidgets.QLabel(parent=Dialog)
        self.AlreadyVoted.setEnabled(True)
        self.AlreadyVoted.setGeometry(QtCore.QRect(100, 270, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.AlreadyVoted.setFont(font)
        self.AlreadyVoted.setAutoFillBackground(False)
        self.AlreadyVoted.setObjectName("AlreadyVoted")
        self.SuccessfullyVoted = QtWidgets.QLabel(parent=Dialog)
        self.SuccessfullyVoted.setEnabled(True)
        self.SuccessfullyVoted.setGeometry(QtCore.QRect(100, 270, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.SuccessfullyVoted.setFont(font)
        self.SuccessfullyVoted.setAutoFillBackground(False)
        self.SuccessfullyVoted.setObjectName("SuccessfullyVoted")
        self.InvalidID = QtWidgets.QLabel(parent=Dialog)
        self.InvalidID.setEnabled(True)
        self.InvalidID.setGeometry(QtCore.QRect(110, 270, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.InvalidID.setFont(font)
        self.InvalidID.setAutoFillBackground(False)
        self.InvalidID.setObjectName("InvalidID")
        self.MustChooseCandidate = QtWidgets.QLabel(parent=Dialog)
        self.MustChooseCandidate.setEnabled(True)
        self.MustChooseCandidate.setGeometry(QtCore.QRect(80, 270, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.MustChooseCandidate.setFont(font)
        self.MustChooseCandidate.setAutoFillBackground(False)
        self.MustChooseCandidate.setObjectName("MustChooseCandidate")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Title.setText(_translate("Dialog", "VOTING APPLICATION"))
        self.IDLabel.setText(_translate("Dialog", "ID"))
        self.CandidatesLabel.setText(_translate("Dialog", "CANDIDATES"))
        self.JaneVote.setText(_translate("Dialog", "Jane"))
        self.JohnVote.setText(_translate("Dialog", "John"))
        self.Submit.setText(_translate("Dialog", "SUBMIT VOTE"))
        self.AlreadyVoted.setText(_translate("Dialog", "Already voted"))
        self.SuccessfullyVoted.setText(_translate("Dialog", "Successfully Voted"))
        self.InvalidID.setText(_translate("Dialog", "Invalid Voter ID"))
        self.MustChooseCandidate.setText(_translate("Dialog", "Must Choose Candidate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())